/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.JButton;

/**
 *
 * @author Aluno
 */
public class Calculadora extends javax.swing.JFrame {
    
    String n1, n2;
    Boolean pNum = true;
    Boolean resetar = false;
    String op;
    double a, b;
    double resultado;
    
    public Calculadora() {
        initComponents();
        n1 = "";
        n2 = "";
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BNum = new javax.swing.ButtonGroup();
        BOp = new javax.swing.ButtonGroup();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B0 = new javax.swing.JButton();
        BDot = new javax.swing.JButton();
        BEqual = new javax.swing.JButton();
        BDiv = new javax.swing.JButton();
        BClear = new javax.swing.JButton();
        BMult = new javax.swing.JButton();
        BSub = new javax.swing.JButton();
        BAdd = new javax.swing.JButton();
        areaTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setAutoRequestFocus(false);

        B7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        B7.setText("7");
        BNum.add(B7);
        B7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B7.setName("1"); // NOI18N
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        B8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        B8.setText("8");
        BNum.add(B8);
        B8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B8.setName("1"); // NOI18N
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        B9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        B9.setText("9");
        BNum.add(B9);
        B9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B9.setName("1"); // NOI18N
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        B4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        B4.setText("4");
        BNum.add(B4);
        B4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B4.setName("1"); // NOI18N
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        B5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        B5.setText("5");
        BNum.add(B5);
        B5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B5.setName("1"); // NOI18N
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        B6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        B6.setText("6");
        BNum.add(B6);
        B6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B6.setName("1"); // NOI18N
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        B1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        B1.setText("1");
        BNum.add(B1);
        B1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B1.setName("1"); // NOI18N
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        B2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        B2.setText("2");
        BNum.add(B2);
        B2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B2.setName("1"); // NOI18N
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        B3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        B3.setText("3");
        BNum.add(B3);
        B3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B3.setName("1"); // NOI18N
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        B0.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        B0.setText("0");
        BNum.add(B0);
        B0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B0.setName("1"); // NOI18N
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        BDot.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BDot.setText(".");
        BNum.add(BDot);
        BDot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BDot.setName("1"); // NOI18N
        BDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClicado(evt);
            }
        });

        BEqual.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BEqual.setText("=");
        BEqual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEqual.setName("1"); // NOI18N
        BEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executar(evt);
            }
        });

        BDiv.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BDiv.setText("/");
        BOp.add(BDiv);
        BDiv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BDiv.setName("1"); // NOI18N
        BDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacao(evt);
            }
        });

        BClear.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BClear.setText("C");
        BClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BClear.setName("1"); // NOI18N
        BClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar(evt);
            }
        });

        BMult.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BMult.setText("x");
        BOp.add(BMult);
        BMult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BMult.setName("1"); // NOI18N
        BMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacao(evt);
            }
        });

        BSub.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BSub.setText("-");
        BOp.add(BSub);
        BSub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BSub.setName("1"); // NOI18N
        BSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacao(evt);
            }
        });

        BAdd.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BAdd.setText("+");
        BOp.add(BAdd);
        BAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAdd.setName("1"); // NOI18N
        BAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacao(evt);
            }
        });

        areaTexto.setEditable(false);
        areaTexto.setColumns(1);
        areaTexto.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        areaTexto.setRows(5);
        areaTexto.setAutoscrolls(false);
        areaTexto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        areaTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.SW_RESIZE_CURSOR));
        areaTexto.setMargin(new java.awt.Insets(6, 6, 6, 6));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(areaTexto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BDot, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BSub, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BMult, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BClear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(areaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BClear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BMult, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSub, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDot, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        B7.getAccessibleContext().setAccessibleName("1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoClicado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoClicado
        JButton botao = (JButton)evt.getSource();
        
        if(resetar)
        {
            n1 = "";
            n2 = "";
            op = "";
            areaTexto.setText("");
            pNum = true;
            resetar = false;
        }
        
        if(pNum == true){
            n1 += botao.getText();
           areaTexto.setText(n1);
        } else {
            n2 += botao.getText();
            areaTexto.setText(n2);
        }
        
        
    }//GEN-LAST:event_botaoClicado

    private void operacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operacao
        JButton botao = (JButton)evt.getSource();
        op = botao.getText();
        areaTexto.setText(op);
        pNum = false;
    }//GEN-LAST:event_operacao

    private void executar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executar
        //JButton botao = (JButton)evt.getSource();
        a = Double.parseDouble(n1);
        b = Double.parseDouble(n2);
        
        if (op == "/"){
           resultado = (a/b);
           areaTexto.setText(n1+" / "+n2+ " = "+resultado);
        }
        else if (op == "x"){
           resultado = (a*b);
           areaTexto.setText(n1+" x "+n2+ " = "+resultado);
        } 
        else if (op == "-"){
           resultado = (a-b);
           areaTexto.setText(n1+" - "+n2+ " = "+resultado);
        } 
        else { // soma(+)
           resultado = (a+b);
           areaTexto.setText(n1+" + "+n2+ " = "+resultado);
        }
        
        resetar = true;
    }//GEN-LAST:event_executar

    private void limpar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar
        n1 = "";
        n2 = "";
        op = "";
        areaTexto.setText("");
        pNum = true;
        resetar = true;
    }//GEN-LAST:event_limpar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton BAdd;
    private javax.swing.JButton BClear;
    private javax.swing.JButton BDiv;
    private javax.swing.JButton BDot;
    private javax.swing.JButton BEqual;
    private javax.swing.JButton BMult;
    private javax.swing.ButtonGroup BNum;
    private javax.swing.ButtonGroup BOp;
    private javax.swing.JButton BSub;
    private javax.swing.JTextArea areaTexto;
    // End of variables declaration//GEN-END:variables
}
